spring:
  datasource:
    password: admin
    username: root
    url: jdbc:mysql:///time_tracker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8888
  servlet:
    context-path: /time-tracker
#    session????
#    session:
#      timeout: -1
